spring:
  application:
    name: hvnh-exam-system

  # ===============================
  # PostgreSQL (Supabase)
  # ===============================
  datasource:
    # ⚠️ QUAN TRỌNG: Phải có ?sslmode=require ở cuối
    # Nếu bị lỗi "Prepared statement... exists", hãy thêm &prepareThreshold=0 vào cuối URL
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.wqxjubsrqsxeejcsokqb
    password: 26a4040725Dat@  
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 580000
      keepalive-time: 30000
      connection-timeout: 30000
      validation-timeout: 3000
      maximum-pool-size:  3
      minimum-idle: 1


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # 👇 FIX LỖI "Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented"
        jdbc:
          lob:
            non_contextual_creation: true

  # ===============================
  # MongoDB (Logs)
  # ===============================
  data:
    mongodb:
      uri: mongodb+srv://hvnh_user:26a4040725Dat@hvnh-cluster.dg2yc6z.mongodb.net/hvnh_logs?appName=hvnh-cluster

  # ===============================
  # Jackson (JSON format)
  # ===============================
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false

# ===============================
# Server
# ===============================
server:
  port: 8080

# ===============================
# Logging
# ===============================
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# ===============================
# 👇 THÊM MỚI: CẤU HÌNH SUPABASE AUTH
# ===============================
supabase:
  # Vào Settings -> API để lấy URL này
  url: https://wqxjubsrqsxeejcsokqb.supabase.co
  
  key:
    service-role-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxeGp1YnNycXN4ZWVqY3Nva3FiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTY2ODkyNSwiZXhwIjoyMDg1MjQ0OTI1fQ.vXEEAhU9-EGBiHMFCjf0Vsd9oimG3RN69xpcNimJ0jk
    
  jwt:
    # Vào Settings -> API -> JWT Settings -> JWT Secret (Dùng để giải mã Token)
    secret: uLnF7dL40N0GTZcsZ7/+ylK4FF7iMLRlwvRxXBRUB+oLFUBC2Kr8ARjXQNekaZ35nhgYfBh5dta0qX5lDQYJeQ==
  
  bucket:
    name: documents
    
gemini:
  api:
    key: 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

