spring:
  application:
    name: hvnh-exam-system

  # ===============================
  # PostgreSQL (Supabase)
  # ===============================
  datasource:
    # ⚠️ QUAN TRỌNG: Phải có ?sslmode=require ở cuối
    # Nếu bị lỗi "Prepared statement... exists", hãy thêm &prepareThreshold=0 vào cuối URL
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.wqxjubsrqsxeejcsokqb
    password: YOUR_DATABASE_PASSWORD  
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 580000
      keepalive-time: 30000
      connection-timeout: 30000
      validation-timeout: 3000
      maximum-pool-size:  3
      minimum-idle: 1


  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # 👇 FIX LỖI "Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented"
        jdbc:
          lob:
            non_contextual_creation: true

  # ===============================
  # MongoDB (Logs)
  # ===============================
  data:
    mongodb:
      uri: mongodb+srv://YOUR_MONGO_USER:YOUR_MONGO_PASSWORD@hvnh-cluster.dg2yc6z.mongodb.net/hvnh_logs?appName=hvnh-cluster

  # ===============================
  # Jackson (JSON format)
  # ===============================
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false

# ===============================
# Server
# ===============================
server:
  port: 8080

# ===============================
# Logging
# ===============================
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

# ===============================
# 👇 THÊM MỚI: CẤU HÌNH SUPABASE AUTH
# ===============================
supabase:
  # Vào Settings -> API để lấy URL này
  url: https://wqxjubsrqsxeejcsokqb.supabase.co
  
  key:
    service-role-key: YOUR_SUPABASE_SERVICE_ROLE_KEY
    
  jwt:
    # Vào Settings -> API -> JWT Settings -> JWT Secret (Dùng để giải mã Token)
    secret: YOUR_SUPABASE_JWT_SECRET
  
  bucket:
    name: documents
    
gemini:
  api:
    key: YOUR_GROQ_API_KEY

